name: Deployment

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version name to deploy"
        required: true
        type: string

permissions:
  contents: write
  pull-requests: write


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Show Version
      run: echo "Deploying version ${{ github.event.inputs.version }}"

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run python Tests
      run: |
        python tests.py

    - name: Build test executable
      run: |
        pyinstaller --onefile tests.py

    - name: Run executable Tests
      run: |
        ./dist/tests



  merge-to-deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Copy files to tmp
        run: |
          rm -rf /tmp/app
          mkdir -p /tmp/app
          cp -r . /tmp/app/

      - name: Checkout or create deploy
        run: |
          git fetch origin

          if git show-ref --verify --quiet refs/remotes/origin/deploy; then
            git checkout deploy
            git pull origin deploy
          else
            git checkout -b deploy
          fi

      - name: Clean old build (keep git)
        run: |
          find . -mindepth 1 -maxdepth 1 ! -name ".git" -exec rm -rf {} +

      - name: Add new executable
        run: |
          cp -r /tmp/app/* . 

      - name: Commit into deploy and create tag
        run: |
          VERSION=${{ github.event.inputs.version }}

          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add -A
          git commit -m"Deploy ${VERSION}" || echo "No changes to commit"

          git tag -a "${VERSION}" -m "Release ${VERSION}"

          git push origin deploy
          git push origin --tags



  deploy_executable:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build executable
        run: |
          pyinstaller --onefile --windowed main.py

      - name: Copy files to tmp
        run: |
          rm -rf /tmp/app
          mkdir -p /tmp/app
          cp -r ./dist/main /tmp/app/SVGParser
          cp -r ./LICENSE /tmp/app/LICENSE
          cp -r ./README.md /tmp/app/README.md

      - name: Checkout or create deploy_executable
        run: |
          git fetch origin

          if git show-ref --verify --quiet refs/remotes/origin/deploy_executable; then
            git checkout deploy_executable
            git pull origin deploy_executable
          else
            git checkout -b deploy_executable
          fi

      - name: Clean old build (keep git)
        run: |
          find . -mindepth 1 -maxdepth 1 ! -name ".git" -exec rm -rf {} +

      - name: Add new executable
        run: |
          cp -r /tmp/app/SVGParser . 
          cp -r /tmp/app/LICENSE . 
          cp -r /tmp/app/README.md . 

      - name: Commit into deploy executable and create tag
        run: |
          VERSION=${{ github.event.inputs.version }}

          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add -A
          git commit -m"Deploy executable ${VERSION}" || echo "No changes to commit"

          git tag -a "${VERSION}-executable" -m "Release ${VERSION} executable"

          git push origin deploy_executable
          git push origin --tags

